---
- hosts:  node02
  become: yes
  vars:
    kubernetes_installed : '1'
    kubernetes_version : "1.15.2-0"
    validated_dockerv: "18.09.8-3.el7"
  tasks:
    - name: disable SELinux
      command: setenforce 0
    - name: disable SELinux on reboot
      selinux:
         state: disabled
    - name: Enable br_netfilter
      command: modprobe br_netfilter
    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
    - name: Remove swapfile from /etc/fstab
      mount:
          name: "{{ item }}"
          fstype: swap
          state: absent
      with_items:
          - swap
          - none
    - name: Disable swap
      command: swapoff -a
    - name: Install the package dependencies for docker-ce
      yum:
         name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
         state: present
         update_cache: true
    - name: Add  YUM Docker repository.
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install Docker
      yum:
         name:
          - 'docker-ce-{{ validated_dockerv }}'
          - 'docker-ce-cli-{{ validated_dockerv }}'
          - containerd.io
         state: present
         update_cache: true
    - name: start Docker
      service:
         name: docker
         state: restarted
         enabled: yes
    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes
    - name: install kubelet
      yum:
          name: 'kubelet-{{ kubernetes_version }}'
          state: present
          update_cache: true
    - name: start kubelet
      service:
         name: kubelet
         enabled: yes
         state: restarted
    - name: Install kubeadm, kubectl
      yum:
         name:
          - 'kubeadm-{{ kubernetes_version }}'
          - 'kubectl-{{ kubernetes_version }}'
         state: present
         update_cache: true
    - name: install kubeadm
      yum:
          name: 'kubeadm-{{ kubernetes_version }}'
          state: present
    - name: install kubectl
      yum:
          name: 'kubectl-{{ kubernetes_version }}'
          state: present
          # allow_downgrade: yes
    - name: Configure node ip
      lineinfile:
        create: yes
        state: present
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

# # worker specific
#     - name: join cluster
#       # shell: "{{ hostvars['k8s-master'].join_command }} --ignore-preflight-errors all  >> /home/vagrant/node_joined.txt"
#       shell: "{{ hostvars['k8s-master'].join_command }} --ignore-preflight-errors all | sudo tee /home/vagrant/node_joined.txt"
#       args:
#         chdir: /home/vagrant
#         creates: node_joined.txt
   # Join the nodes to the Kubernetes cluster
    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777
    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

  roles:
    - common
